added config file, cleaned up some mess

diff --git a/hooks/install b/hooks/install
--- a/hooks/install
+++ b/hooks/install
@@ -1,26 +1,41 @@
 #!/bin/bash
-
 set -eux # -x for verbose logging to juju debug-log
+
+HOME=`dirname $0`
+. $HOME/common.sh
+
 juju-log "Installing required Packages via apt-get - java"
+# was giving errors trying to install jre without update first.
 apt-get update
 apt-get -y install default-jre-headless curl
 juju-log "Install upstart init script"
 install -o root -g root -m 0644 files/charm/logstash-indexer.conf /etc/init/logstash-indexer.conf
+sed -i "s|BASEPATH|${BASEPATH}|g" /etc/init/logstash-indexer.conf
 juju-log "create logstash user"
-useradd logstash
+useradd ${USER}
 juju-log "create skeleton dir"
-mkdir -p /usr/local/logstash/bin
-mkdir -p /usr/local/logstash/conf.d
-mkdir -p /usr/local/logstash/data
-juju-log "download and install logstash and create config files"
-# using version 1.1.1 as some newer ones have some gem errors with the web search
-wget -O /usr/local/logstash/bin/logstash-monolithic.jar http://semicomplete.com/files/logstash/logstash-1.1.1-monolithic.jar
-echo 'input {  file {     type => "syslog"    path => "/var/log/syslog" sincedb_path => "/usr/local/logstash" } }' > /usr/local/logstash/conf.d/input-syslog.conf
-echo 'output {  elasticsearch {    embedded => true  } }' > /usr/local/logstash/conf.d/output-embedded-es.conf
+mkdir -p ${BASEPATH}/bin
+mkdir -p ${BASEPATH}/conf.d
+mkdir -p ${BASEPATH}/data
+juju-log "install logstash and create config files"
+# Check if a local copy of the jar exists
+if [ -f files/charm/logstash-${VERSION}-monolithic.jar ]
+then
+  install -o root -g root -m 0644 files/charm/logstash-${VERSION}-monolithic.jar ${BASEPATH}/bin/logstash-monolithic.jar
+else
+  # Download logstash monolithic jar and checksum
+  wget -O ${BASEPATH}/bin/logstash-monolithic.jar ${BASEURL}/logstash-${VERSION}-monolithic.jar
+  if [[ $(md5sum "${BASEPATH}/bin/logstash-monolithic.jar" | cut -d " " -f 1) != ${CHECKSUM} ]]; then
+    juju-log --log-level CRITICAL "Checksum of ${BASEPATH}/bin/logstash-monolithic.jar failed"
+    exit 1
+  fi
+fi
+echo 'input {  file {     type => "syslog"    path => "/var/log/syslog" sincedb_path => "${BASEPATH}" } }' > ${BASEPATH}/conf.d/input-syslog.conf
+echo 'output {  elasticsearch {    embedded => true  } }' > ${BASEPATH}/conf.d/output-embedded-es.conf
 # the below is noisy in the juju debug-log... but useful ... can comment it out.
 # echo 'output { stdout { debug => true debug_format => "json"} }' > /usr/local/logstash/conf.d/output-stdout.conf
 juju-log "create log file and pwn it"
 touch /var/log/logstash-indexer.log
-chown logstash. /var/log/logstash-indexer.log
-juju-log "Make sure logstash user owns the whole kit and kaboodle"
-chown -R logstash. /usr/local/logstash
+chown ${USER}. /var/log/logstash-indexer.log
+juju-log "Make sure ${USER} user owns the whole kit and kaboodle"
+chown -R ${USER}. ${BASEPATH}
